### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by ericandrewlewis** [FullScreenShenanigans/FullScreenMario#278]
When I run `grunt`, I get an error related to TypeScript processing:

```bash
$ grunt
Running "tslint:files" (tslint) task
>> 1 file lint free.

Running "typescript:base" (typescript) task
>> Source/FullScreenMario.ts(28,9): error TS2322: Type '{ [x: string]: undefined; "audio": undefined; "collisions": undefined; "editor": undefined; "gene...' is not assignable to type 'IGameStartrStoredSettings'.
>>   Property '"math"' is missing in type '{ [x: string]: undefined; "audio": undefined; "collisions": undefined; "editor": undefined; "gene...'.
>> Source/FullScreenMario.ts(328,29): error TS2339: Property 'clearAll' does not exist on type 'IAudioPlayr'.
>> Source/FullScreenMario.ts(332,29): error TS2339: Property 'hideContainer' does not exist on type 'IItemsHoldr'.
>> Source/FullScreenMario.ts(347,37): error TS2339: Property 'displayContainer' does not exist on type 'IItemsHoldr'.
>> Source/FullScreenMario.ts(819,33): error TS2339: Property 'decrease' does not exist on type 'IItemsHoldr'.
>> Source/FullScreenMario.ts(2587,17): error TS2322: Type 'IMapsCreatr' is not assignable to type 'MapsCreatr'.
>>   Property 'ObjectMaker' is missing in type 'IMapsCreatr'.
>> Source/FullScreenMario.ts(2589,17): error TS2322: Type 'IMapsHandlr' is not assignable to type 'MapsHandlr'.
>>   Property 'MapsCreator' is missing in type 'IMapsHandlr'.
>> Source/FullScreenMario.ts(2652,17): error TS2322: Type 'IMapsCreatr' is not assignable to type 'MapsCreatr'.
>> Source/FullScreenMario.ts(2654,17): error TS2322: Type 'IMapsHandlr' is not assignable to type 'MapsHandlr'.
>> Source/FullScreenMario.ts(2706,17): error TS2322: Type 'IMapsCreatr' is not assignable to type 'MapsCreatr'.
>> Source/FullScreenMario.ts(2708,17): error TS2322: Type 'IMapsHandlr' is not assignable to type 'MapsHandlr'.
>> Source/FullScreenMario.ts(3607,35): error TS2339: Property 'clearAll' does not exist on type 'IAudioPlayr'.
>> Source/FullScreenMario.ts(3735,43): error TS2339: Property 'decrease' does not exist on type 'IItemsHoldr'.
>> Source/FullScreenMario.ts(6568,29): error TS2339: Property 'clearAll' does not exist on type 'IAudioPlayr'.
>> Source/FullScreenMario.ts(6570,29): error TS2339: Property 'decrease' does not exist on type 'IItemsHoldr'.
>> Source/FullScreenMario.ts(6878,29): error TS2339: Property 'clearAll' does not exist on type 'IAudioPlayr'.
>> Source/FullScreenMario.ts(7305,17): error TS2322: Type 'IMapsCreatr' is not assignable to type 'MapsCreatr'.
>> Source/FullScreenMario.ts(7306,17): error TS2322: Type 'IMapsHandlr' is not assignable to type 'MapsHandlr'.
>> Source/References/GameStartr-0.2.0.ts(13,1): error TS6053: File 'Source/References/MathDecidr-0.2.0.ts' not found.
>> Source/References/GameStartr-0.2.0.ts(228,22): error TS2304: Cannot find name 'MathDecidr'.
>> Source/References/GameStartr-0.2.0.ts(377,29): error TS2304: Cannot find name 'MathDecidr'.
>> Source/References/GameStartr-0.2.0.ts(843,43): error TS2304: Cannot find name 'MathDecidr'.
Warning: Task "typescript:base" failed. Use --force to continue.
Error: Task "typescript:base" failed.
    at Task.<anonymous> (/Users/eric/Downloads/FullScreenMario-master/node_modules/grunt/lib/util/task.js:205:15)
    at null._onTimeout (/Users/eric/Downloads/FullScreenMario-master/node_modules/grunt/lib/util/task.js:241:33)
    at Timer.listOnTimeout (timers.js:110:15)

Aborted due to warnings.
```

**Comment by JoshuaKGoldberg** [comment]
Issues confirmed, working on hotfix now...

**Comment by JoshuaKGoldberg** [comment]
Sorry about that - builds should be running normally.

**Comment by ericandrewlewis** [comment]
:smile:
